name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Read VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: ./landing-page
          file: ./landing-page/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-business-agent:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/ai-business-agent:latest
          
      # Build Backend image
      - name: Build & Push AI-Agent API
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: ./agent_code
          file: ./agent_code/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/intelligent-business-ai-agent:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/intelligent-business-ai-agent:latest