name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ./landing-page
          file: ./landing-page/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-business-agent:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/ai-business-agent:latest
          
      # Build Backend image
      - name: Build & Push AI-Agent API
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ./agent_code
          file: ./agent_code/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/intelligent-business-ai-agent:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/intelligent-business-ai-agent:latest